# переменные с текстом билетов

ticket_python_1 = 'БИЛЕТ №1'
ticket_python_2 = 'БИЛЕТ №2'
ticket_python_3 = 'БИЛЕТ №3'
ticket_python_4 = 'БИЛЕТ №4'
ticket_python_5 = 'БИЛЕТ №5'
ticket_python_6 = 'БИЛЕТ №6'
ticket_python_7 = 'БИЛЕТ №7'
ticket_python_8 = 'БИЛЕТ №8'
ticket_python_9 = 'БИЛЕТ №9'

ticket_HTML_1 = 'БИЛЕТ №1'
ticket_HTML_2 = 'БИЛЕТ №2'
ticket_HTML_3 = 'БИЛЕТ №3'
ticket_HTML_4 = 'БИЛЕТ №4'
ticket_HTML_5 = 'БИЛЕТ №5'
ticket_HTML_6 = 'БИЛЕТ №6'
ticket_HTML_7 = 'БИЛЕТ №7'
ticket_HTML_8 = 'БИЛЕТ №8'
ticket_HTML_9 = 'БИЛЕТ №9'

ticket_SQL_1 = 'БИЛЕТ №1'
ticket_SQL_2 = 'БИЛЕТ №2'
ticket_SQL_3 = 'БИЛЕТ №3'
ticket_SQL_4 = 'БИЛЕТ №4'
ticket_SQL_5 = 'БИЛЕТ №5'
ticket_SQL_6 = 'БИЛЕТ №6'
ticket_SQL_7 = 'БИЛЕТ №7'
ticket_SQL_8 = 'БИЛЕТ №8'
ticket_SQL_9 = 'БИЛЕТ №9'